package org.intrigger.ultimate_market.utils;

import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

public class ItemCategoriesProcessor {

    YamlConfiguration configuration;

    public ArrayList<String> titles;
    public Map<String, ItemFilterNotation> filterNotations = new HashMap<>();
    public Map<String, String> display_names;

    public ItemCategoriesProcessor(String configFilename){

        display_names = new HashMap<>();

        if (!new File(configFilename).exists()){
            generateItemCategoriesYML(configFilename);
        }

        configuration = YamlConfiguration.loadConfiguration(new File(configFilename));
        titles = new ArrayList<>(configuration.getKeys(false));
        for (String title: titles){
            String name = configuration.getString(title + "." + "title");
            int slot = configuration.getInt(title + "." + "slot");
            String material = configuration.getString(title + "." + "material");
            ArrayList<String> filters = new ArrayList<>(configuration.getStringList(title + "." + "items"));

            assert name != null;
            name = name.replace("&", "§");

            assert material != null;
            filterNotations.put(title, new ItemFilterNotation(title, name, new ArrayList<>(), slot, filters, Material.getMaterial(material)));
            display_names.put(title, name);
        }

        for (Map.Entry<String, ItemFilterNotation> notation: filterNotations.entrySet()){
            for (String f: notation.getValue().filters){
                if (Material.getMaterial(f) == null) {
                    System.out.println(ChatColor.RED + "Item Categories YML Configuration file error: wrong material " + f);
                }
            }
        }
    }

    public void generateItemCategoriesYML(String configFileName){
        String yml_str =
                "alchemistry:\n" +
                " title: \"&2&lAlchemistry\"\n" +
                " slot: 9\n" +
                " material: \"GLOWSTONE_DUST\"\n" +
                " items: \n" +
                "  - 'BLAZE_POWDER'\n" +
                "  - 'BREWING_STAND'\n" +
                "  - 'BROWN_MUSHROOM'\n" +
                "  - 'DRAGON_BREATH'\n" +
                "  - 'FERMENTED_SPIDER_EYE'\n" +
                "  - 'GHAST_TEAR'\n" +
                "  - 'GLASS_BOTTLE'\n" +
                "  - 'GLISTERING_MELON_SLICE'\n" +
                "  - 'GLOWSTONE'\n" +
                "  - 'GLOWSTONE_DUST'\n" +
                "  - 'GUNPOWDER'\n" +
                "  - 'NETHER_WART'\n" +
                "  - 'PUFFERFISH'\n" +
                "  - 'REDSTONE'\n" +
                "  - 'SCUTE'\n" +
                "  - 'SPIDER_EYE'\n" +
                "  - 'SUGAR'\n" +
                "armor:\n" +
                " title: \"&2&lArmor\"\n" +
                " slot: 10\n" +
                " material: \"NETHERITE_CHESTPLATE\"\n" +
                " items: \n" +
                "  - 'CHAINMAIL_BOOTS'\n" +
                "  - 'CHAINMAIL_CHESTPLATE'\n" +
                "  - 'CHAINMAIL_HELMET'\n" +
                "  - 'CHAINMAIL_LEGGINGS'\n" +
                "  - 'DIAMOND_BOOTS'\n" +
                "  - 'DIAMOND_CHESTPLATE'\n" +
                "  - 'DIAMOND_HELMET'\n" +
                "  - 'DIAMOND_HORSE_ARMOR'\n" +
                "  - 'DIAMOND_LEGGINGS'\n" +
                "  - 'ELYTRA'\n" +
                "  - 'GOLDEN_BOOTS'\n" +
                "  - 'GOLDEN_CHESTPLATE'\n" +
                "  - 'GOLDEN_HELMET'\n" +
                "  - 'GOLDEN_HORSE_ARMOR'\n" +
                "  - 'GOLDEN_LEGGINGS'\n" +
                "  - 'IRON_BOOTS'\n" +
                "  - 'IRON_CHESTPLATE'\n" +
                "  - 'IRON_HELMET'\n" +
                "  - 'IRON_LEGGINGS'\n" +
                "  - 'LEATHER_BOOTS'\n" +
                "  - 'LEATHER_CHESTPLATE'\n" +
                "  - 'LEATHER_HELMET'\n" +
                "  - 'LEATHER_HORSE_ARMOR'\n" +
                "  - 'LEATHER_LEGGINGS'\n" +
                "  - 'NETHERITE_BOOTS'\n" +
                "  - 'NETHERITE_CHESTPLATE'\n" +
                "  - 'NETHERITE_HELMET'\n" +
                "  - 'NETHERITE_LEGGINGS'\n" +
                "  - 'TURTLE_HELMET'\n" +
                "building:\n" +
                " title: \"&2&lBuilding Blocks\"\n" +
                " slot: 11\n" +
                " material: \"STONE_BRICKS\"\n" +
                " items: \n" +
                "  - 'ACACIA_LEAVES'\n" +
                "  - 'ACACIA_LOG'\n" +
                "  - 'ACACIA_PLANKS'\n" +
                "  - 'ACACIA_SLAB'\n" +
                "  - 'ACACIA_STAIRS'\n" +
                "  - 'ACACIA_WOOD'\n" +
                "  - 'AIR'\n" +
                "  - 'ANCIENT_DEBRIS'\n" +
                "  - 'ANDESITE'\n" +
                "  - 'ANDESITE_SLAB'\n" +
                "  - 'ANDESITE_STAIRS'\n" +
                "  - 'ANDESITE_WALL'\n" +
                "  - 'BASALT'\n" +
                "  - 'BEDROCK'\n" +
                "  - 'BIRCH_LEAVES'\n" +
                "  - 'BIRCH_LOG'\n" +
                "  - 'BIRCH_PLANKS'\n" +
                "  - 'BIRCH_SLAB'\n" +
                "  - 'BIRCH_STAIRS'\n" +
                "  - 'BIRCH_TRAPDOOR'\n" +
                "  - 'BIRCH_WOOD'\n" +
                "  - 'BLACKSTONE'\n" +
                "  - 'BLACKSTONE_SLAB'\n" +
                "  - 'BLACKSTONE_STAIRS'\n" +
                "  - 'BLACKSTONE_WALL'\n" +
                "  - 'BLACK_CONCRETE'\n" +
                "  - 'BLACK_CONCRETE_POWDER'\n" +
                "  - 'BLACK_GLAZED_TERRACOTTA'\n" +
                "  - 'BLACK_STAINED_GLASS'\n" +
                "  - 'BLACK_STAINED_GLASS_PANE'\n" +
                "  - 'BLACK_TERRACOTTA'\n" +
                "  - 'BLACK_WOOL'\n" +
                "  - 'BLUE_CONCRETE'\n" +
                "  - 'BLUE_CONCRETE_POWDER'\n" +
                "  - 'BLUE_GLAZED_TERRACOTTA'\n" +
                "  - 'BLUE_ICE'\n" +
                "  - 'BLUE_STAINED_GLASS'\n" +
                "  - 'BLUE_STAINED_GLASS_PANE'\n" +
                "  - 'BLUE_TERRACOTTA'\n" +
                "  - 'BLUE_WOOL'\n" +
                "  - 'BRAIN_CORAL'\n" +
                "  - 'BRAIN_CORAL_BLOCK'\n" +
                "  - 'BRICK'\n" +
                "  - 'BRICKS'\n" +
                "  - 'BRICK_SLAB'\n" +
                "  - 'BRICK_STAIRS'\n" +
                "  - 'BRICK_WALL'\n" +
                "  - 'BROWN_CONCRETE'\n" +
                "  - 'BROWN_CONCRETE_POWDER'\n" +
                "  - 'BROWN_GLAZED_TERRACOTTA'\n" +
                "  - 'BROWN_STAINED_GLASS'\n" +
                "  - 'BROWN_STAINED_GLASS_PANE'\n" +
                "  - 'BROWN_TERRACOTTA'\n" +
                "  - 'BUBBLE_CORAL_BLOCK'\n" +
                "  - 'CHISELED_NETHER_BRICKS'\n" +
                "  - 'CHISELED_POLISHED_BLACKSTONE'\n" +
                "  - 'CHISELED_QUARTZ_BLOCK'\n" +
                "  - 'CHISELED_RED_SANDSTONE'\n" +
                "  - 'CHISELED_SANDSTONE'\n" +
                "  - 'CHISELED_STONE_BRICKS'\n" +
                "  - 'CLAY'\n" +
                "  - 'COARSE_DIRT'\n" +
                "  - 'COBBLESTONE'\n" +
                "  - 'COBBLESTONE_SLAB'\n" +
                "  - 'COBBLESTONE_STAIRS'\n" +
                "  - 'COBBLESTONE_WALL'\n" +
                "  - 'CRACKED_NETHER_BRICKS'\n" +
                "  - 'CRACKED_POLISHED_BLACKSTONE_BRICKS'\n" +
                "  - 'CRACKED_STONE_BRICKS'\n" +
                "  - 'CRIMSON_HYPHAE'\n" +
                "  - 'CRIMSON_NYLIUM'\n" +
                "  - 'CRIMSON_PLANKS'\n" +
                "  - 'CRIMSON_SLAB'\n" +
                "  - 'CRIMSON_STAIRS'\n" +
                "  - 'CRIMSON_STEM'\n" +
                "  - 'CRYING_OBSIDIAN'\n" +
                "  - 'CUT_RED_SANDSTONE_SLAB'\n" +
                "  - 'CUT_SANDSTONE_SLAB'\n" +
                "  - 'CUT_RED_SANDSTONE'\n" +
                "  - 'CUT_SANDSTONE'\n" +
                "  - 'CYAN_CONCRETE'\n" +
                "  - 'CYAN_CONCRETE_POWDER'\n" +
                "  - 'CYAN_GLAZED_TERRACOTTA'\n" +
                "  - 'CYAN_STAINED_GLASS'\n" +
                "  - 'CYAN_STAINED_GLASS_PANE'\n" +
                "  - 'CYAN_TERRACOTTA'\n" +
                "  - 'DARK_OAK_LEAVES'\n" +
                "  - 'DARK_OAK_LOG'\n" +
                "  - 'DARK_OAK_PLANKS'\n" +
                "  - 'DARK_OAK_SLAB'\n" +
                "  - 'DARK_OAK_STAIRS'\n" +
                "  - 'DARK_OAK_WOOD'\n" +
                "  - 'DARK_PRISMARINE'\n" +
                "  - 'DARK_PRISMARINE_SLAB'\n" +
                "  - 'DARK_PRISMARINE_STAIRS'\n" +
                "  - 'DEAD_BRAIN_CORAL_BLOCK'\n" +
                "  - 'DEAD_BUBBLE_CORAL_BLOCK'\n" +
                "  - 'DEAD_FIRE_CORAL_BLOCK'\n" +
                "  - 'DEAD_HORN_CORAL_BLOCK'\n" +
                "  - 'DEAD_TUBE_CORAL_BLOCK'\n" +
                "  - 'DIORITE'\n" +
                "  - 'DIORITE_SLAB'\n" +
                "  - 'DIORITE_STAIRS'\n" +
                "  - 'DIORITE_WALL'\n" +
                "  - 'DIRT'\n" +
                "  - 'END_STONE'\n" +
                "  - 'END_STONE_BRICKS'\n" +
                "  - 'END_STONE_BRICK_SLAB'\n" +
                "  - 'END_STONE_BRICK_STAIRS'\n" +
                "  - 'END_STONE_BRICK_WALL'\n" +
                "  - 'FIRE_CORAL_BLOCK'\n" +
                "  - 'GLASS'\n" +
                "  - 'GLASS_PANE'\n" +
                "  - 'GRANITE'\n" +
                "  - 'GRANITE_SLAB'\n" +
                "  - 'GRANITE_STAIRS'\n" +
                "  - 'GRANITE_WALL'\n" +
                "  - 'GRASS_BLOCK'\n" +
                "  - 'GRASS_PATH'\n" +
                "  - 'GRAVEL'\n" +
                "  - 'GRAY_CONCRETE'\n" +
                "  - 'GRAY_CONCRETE_POWDER'\n" +
                "  - 'GRAY_GLAZED_TERRACOTTA'\n" +
                "  - 'GRAY_STAINED_GLASS'\n" +
                "  - 'GRAY_STAINED_GLASS_PANE'\n" +
                "  - 'GRAY_TERRACOTTA'\n" +
                "  - 'GREEN_CONCRETE'\n" +
                "  - 'GREEN_CONCRETE_POWDER'\n" +
                "  - 'GREEN_GLAZED_TERRACOTTA'\n" +
                "  - 'GREEN_STAINED_GLASS'\n" +
                "  - 'GREEN_STAINED_GLASS_PANE'\n" +
                "  - 'GREEN_TERRACOTTA'\n" +
                "  - 'HORN_CORAL_BLOCK'\n" +
                "  - 'ICE'\n" +
                "  - 'INFESTED_CHISELED_STONE_BRICKS'\n" +
                "  - 'INFESTED_COBBLESTONE'\n" +
                "  - 'INFESTED_CRACKED_STONE_BRICKS'\n" +
                "  - 'INFESTED_MOSSY_STONE_BRICKS'\n" +
                "  - 'INFESTED_STONE'\n" +
                "  - 'INFESTED_STONE_BRICKS'\n" +
                "  - 'JUNGLE_LOG'\n" +
                "  - 'JUNGLE_PLANKS'\n" +
                "  - 'JUNGLE_SLAB'\n" +
                "  - 'JUNGLE_STAIRS'\n" +
                "  - 'JUNGLE_WOOD'\n" +
                "  - 'LIGHT_GRAY_STAINED_GLASS'\n" +
                "  - 'LIGHT_BLUE_CONCRETE'\n" +
                "  - 'LIGHT_BLUE_CONCRETE_POWDER'\n" +
                "  - 'LIGHT_BLUE_GLAZED_TERRACOTTA'\n" +
                "  - 'LIGHT_BLUE_STAINED_GLASS'\n" +
                "  - 'LIGHT_BLUE_STAINED_GLASS_PANE'\n" +
                "  - 'LIGHT_BLUE_TERRACOTTA'\n" +
                "  - 'LIGHT_GRAY_CONCRETE'\n" +
                "  - 'LIGHT_GRAY_CONCRETE_POWDER'\n" +
                "  - 'LIGHT_GRAY_GLAZED_TERRACOTTA'\n" +
                "  - 'LIGHT_GRAY_STAINED_GLASS_PANE'\n" +
                "  - 'LIGHT_GRAY_TERRACOTTA'\n" +
                "  - 'LIME_CONCRETE'\n" +
                "  - 'LIME_CONCRETE_POWDER'\n" +
                "  - 'LIME_GLAZED_TERRACOTTA'\n" +
                "  - 'LIME_STAINED_GLASS'\n" +
                "  - 'LIME_STAINED_GLASS_PANE'\n" +
                "  - 'LIME_TERRACOTTA'\n" +
                "  - 'MAGENTA_CONCRETE'\n" +
                "  - 'MAGENTA_CONCRETE_POWDER'\n" +
                "  - 'MAGENTA_GLAZED_TERRACOTTA'\n" +
                "  - 'MAGENTA_STAINED_GLASS'\n" +
                "  - 'MAGENTA_STAINED_GLASS_PANE'\n" +
                "  - 'MAGENTA_TERRACOTTA'\n" +
                "  - 'MAGMA_BLOCK'\n" +
                "  - 'MOSSY_COBBLESTONE'\n" +
                "  - 'MOSSY_COBBLESTONE_SLAB'\n" +
                "  - 'MOSSY_COBBLESTONE_STAIRS'\n" +
                "  - 'MOSSY_COBBLESTONE_WALL'\n" +
                "  - 'MOSSY_STONE_BRICKS'\n" +
                "  - 'MOSSY_STONE_BRICK_SLAB'\n" +
                "  - 'MOSSY_STONE_BRICK_STAIRS'\n" +
                "  - 'MOSSY_STONE_BRICK_WALL'\n" +
                "  - 'MYCELIUM'\n" +
                "  - 'NETHERRACK'\n" +
                "  - 'NETHER_BRICK'\n" +
                "  - 'NETHER_BRICKS'\n" +
                "  - 'NETHER_BRICK_SLAB'\n" +
                "  - 'NETHER_BRICK_STAIRS'\n" +
                "  - 'NETHER_BRICK_WALL'\n" +
                "  - 'OAK_LEAVES'\n" +
                "  - 'OAK_LOG'\n" +
                "  - 'OAK_PLANKS'\n" +
                "  - 'OAK_SLAB'\n" +
                "  - 'OAK_STAIRS'\n" +
                "  - 'OAK_WOOD'\n" +
                "  - 'OBSIDIAN'\n" +
                "  - 'ORANGE_CONCRETE'\n" +
                "  - 'ORANGE_CONCRETE_POWDER'\n" +
                "  - 'ORANGE_GLAZED_TERRACOTTA'\n" +
                "  - 'ORANGE_STAINED_GLASS'\n" +
                "  - 'ORANGE_STAINED_GLASS_PANE'\n" +
                "  - 'ORANGE_TERRACOTTA'\n" +
                "  - 'PACKED_ICE'\n" +
                "  - 'PETRIFIED_OAK_SLAB'\n" +
                "  - 'PINK_CONCRETE'\n" +
                "  - 'PINK_CONCRETE_POWDER'\n" +
                "  - 'PINK_GLAZED_TERRACOTTA'\n" +
                "  - 'PINK_STAINED_GLASS'\n" +
                "  - 'PINK_STAINED_GLASS_PANE'\n" +
                "  - 'PINK_TERRACOTTA'\n" +
                "  - 'PODZOL'\n" +
                "  - 'POLISHED_ANDESITE'\n" +
                "  - 'POLISHED_ANDESITE_SLAB'\n" +
                "  - 'POLISHED_ANDESITE_STAIRS'\n" +
                "  - 'POLISHED_BASALT'\n" +
                "  - 'POLISHED_BLACKSTONE'\n" +
                "  - 'POLISHED_BLACKSTONE_BRICKS'\n" +
                "  - 'POLISHED_BLACKSTONE_BRICK_SLAB'\n" +
                "  - 'POLISHED_BLACKSTONE_BRICK_STAIRS'\n" +
                "  - 'POLISHED_BLACKSTONE_BRICK_WALL'\n" +
                "  - 'POLISHED_BLACKSTONE_SLAB'\n" +
                "  - 'POLISHED_BLACKSTONE_STAIRS'\n" +
                "  - 'POLISHED_BLACKSTONE_WALL'\n" +
                "  - 'POLISHED_DIORITE'\n" +
                "  - 'POLISHED_DIORITE_SLAB'\n" +
                "  - 'POLISHED_DIORITE_STAIRS'\n" +
                "  - 'POLISHED_GRANITE'\n" +
                "  - 'POLISHED_GRANITE_SLAB'\n" +
                "  - 'POLISHED_GRANITE_STAIRS'\n" +
                "  - 'PRISMARINE_BRICKS'\n" +
                "  - 'PRISMARINE_BRICK_SLAB'\n" +
                "  - 'PRISMARINE_BRICK_STAIRS'\n" +
                "  - 'PRISMARINE_SLAB'\n" +
                "  - 'PRISMARINE_STAIRS'\n" +
                "  - 'PRISMARINE_WALL'\n" +
                "  - 'PURPLE_CONCRETE'\n" +
                "  - 'PURPLE_CONCRETE_POWDER'\n" +
                "  - 'PURPLE_GLAZED_TERRACOTTA'\n" +
                "  - 'PURPLE_STAINED_GLASS'\n" +
                "  - 'PURPLE_STAINED_GLASS_PANE'\n" +
                "  - 'PURPLE_TERRACOTTA'\n" +
                "  - 'PURPUR_BLOCK'\n" +
                "  - 'PURPUR_PILLAR'\n" +
                "  - 'PURPUR_SLAB'\n" +
                "  - 'PURPUR_STAIRS'\n" +
                "  - 'QUARTZ_BRICKS'\n" +
                "  - 'QUARTZ_PILLAR'\n" +
                "  - 'QUARTZ_SLAB'\n" +
                "  - 'QUARTZ_STAIRS'\n" +
                "  - 'RED_CONCRETE'\n" +
                "  - 'RED_CONCRETE_POWDER'\n" +
                "  - 'RED_GLAZED_TERRACOTTA'\n" +
                "  - 'RED_MUSHROOM_BLOCK'\n" +
                "  - 'RED_NETHER_BRICKS'\n" +
                "  - 'RED_NETHER_BRICK_SLAB'\n" +
                "  - 'RED_NETHER_BRICK_STAIRS'\n" +
                "  - 'RED_NETHER_BRICK_WALL'\n" +
                "  - 'RED_SAND'\n" +
                "  - 'RED_SANDSTONE'\n" +
                "  - 'RED_SANDSTONE_SLAB'\n" +
                "  - 'RED_SANDSTONE_STAIRS'\n" +
                "  - 'RED_SANDSTONE_WALL'\n" +
                "  - 'RED_STAINED_GLASS'\n" +
                "  - 'RED_STAINED_GLASS_PANE'\n" +
                "  - 'RED_TERRACOTTA'\n" +
                "  - 'SAND'\n" +
                "  - 'SANDSTONE'\n" +
                "  - 'SANDSTONE_SLAB'\n" +
                "  - 'SANDSTONE_STAIRS'\n" +
                "  - 'SANDSTONE_WALL'\n" +
                "  - 'SCAFFOLDING'\n" +
                "  - 'SHROOMLIGHT'\n" +
                "  - 'SMOOTH_QUARTZ'\n" +
                "  - 'SMOOTH_QUARTZ_SLAB'\n" +
                "  - 'SMOOTH_QUARTZ_STAIRS'\n" +
                "  - 'SMOOTH_RED_SANDSTONE'\n" +
                "  - 'SMOOTH_RED_SANDSTONE_SLAB'\n" +
                "  - 'SMOOTH_RED_SANDSTONE_STAIRS'\n" +
                "  - 'SMOOTH_SANDSTONE'\n" +
                "  - 'SMOOTH_SANDSTONE_SLAB'\n" +
                "  - 'SMOOTH_SANDSTONE_STAIRS'\n" +
                "  - 'SMOOTH_STONE'\n" +
                "  - 'SMOOTH_STONE_SLAB'\n" +
                "  - 'SNOW'\n" +
                "  - 'SNOW_BLOCK'\n" +
                "  - 'SOUL_SAND'\n" +
                "  - 'SOUL_SOIL'\n" +
                "  - 'SPRUCE_LEAVES'\n" +
                "  - 'SPRUCE_LOG'\n" +
                "  - 'SPRUCE_PLANKS'\n" +
                "  - 'SPRUCE_SLAB'\n" +
                "  - 'SPRUCE_STAIRS'\n" +
                "  - 'SPRUCE_WOOD'\n" +
                "  - 'STONE'\n" +
                "  - 'STONE_BRICKS'\n" +
                "  - 'STONE_BRICK_SLAB'\n" +
                "  - 'STONE_BRICK_STAIRS'\n" +
                "  - 'STONE_BRICK_WALL'\n" +
                "  - 'STONE_SLAB'\n" +
                "  - 'STONE_STAIRS'\n" +
                "  - 'STRIPPED_ACACIA_LOG'\n" +
                "  - 'STRIPPED_ACACIA_WOOD'\n" +
                "  - 'STRIPPED_BIRCH_LOG'\n" +
                "  - 'STRIPPED_CRIMSON_HYPHAE'\n" +
                "  - 'STRIPPED_CRIMSON_STEM'\n" +
                "  - 'STRIPPED_DARK_OAK_LOG'\n" +
                "  - 'STRIPPED_DARK_OAK_WOOD'\n" +
                "  - 'STRIPPED_JUNGLE_LOG'\n" +
                "  - 'STRIPPED_JUNGLE_WOOD'\n" +
                "  - 'STRIPPED_OAK_LOG'\n" +
                "  - 'STRIPPED_OAK_WOOD'\n" +
                "  - 'STRIPPED_SPRUCE_LOG'\n" +
                "  - 'STRIPPED_WARPED_HYPHAE'\n" +
                "  - 'STRIPPED_WARPED_STEM'\n" +
                "  - 'TERRACOTTA'\n" +
                "  - 'TUBE_CORAL_BLOCK'\n" +
                "  - 'WARPED_HYPHAE'\n" +
                "  - 'WARPED_NYLIUM'\n" +
                "  - 'WARPED_PLANKS'\n" +
                "  - 'WARPED_SLAB'\n" +
                "  - 'WARPED_STAIRS'\n" +
                "  - 'WARPED_STEM'\n" +
                "  - 'WHITE_CONCRETE'\n" +
                "  - 'WHITE_CONCRETE_POWDER'\n" +
                "  - 'WHITE_GLAZED_TERRACOTTA'\n" +
                "  - 'WHITE_STAINED_GLASS'\n" +
                "  - 'WHITE_STAINED_GLASS_PANE'\n" +
                "  - 'WHITE_TERRACOTTA'\n" +
                "  - 'YELLOW_CONCRETE'\n" +
                "  - 'YELLOW_CONCRETE_POWDER'\n" +
                "  - 'YELLOW_GLAZED_TERRACOTTA'\n" +
                "  - 'YELLOW_STAINED_GLASS'\n" +
                "  - 'YELLOW_STAINED_GLASS_PANE'\n" +
                "  - 'YELLOW_TERRACOTTA'\n" +
                "decorations:\n" +
                " title: \"&2&lDecorative Blocks\"\n" +
                " slot: 12\n" +
                " material: \"PAINTING\"\n" +
                " items: \n" +
                "  - 'ACACIA_DOOR'\n" +
                "  - 'ACACIA_FENCE'\n" +
                "  - 'ACACIA_FENCE_GATE'\n" +
                "  - 'ACACIA_SIGN'\n" +
                "  - 'ACACIA_SLAB'\n" +
                "  - 'ACACIA_STAIRS'\n" +
                "  - 'ACACIA_TRAPDOOR'\n" +
                "  - 'ACACIA_WALL_SIGN'\n" +
                "  - 'ALLIUM'\n" +
                "  - 'ANDESITE_SLAB'\n" +
                "  - 'ANDESITE_STAIRS'\n" +
                "  - 'ANDESITE_WALL'\n" +
                "  - 'ANVIL'\n" +
                "  - 'ARMOR_STAND'\n" +
                "  - 'AZURE_BLUET'\n" +
                "  - 'BARREL'\n" +
                "  - 'BEEHIVE'\n" +
                "  - 'BEE_NEST'\n" +
                "  - 'BELL'\n" +
                "  - 'BIRCH_DOOR'\n" +
                "  - 'BIRCH_FENCE'\n" +
                "  - 'BIRCH_FENCE_GATE'\n" +
                "  - 'BIRCH_SIGN'\n" +
                "  - 'BIRCH_SLAB'\n" +
                "  - 'BIRCH_STAIRS'\n" +
                "  - 'BIRCH_TRAPDOOR'\n" +
                "  - 'BIRCH_WALL_SIGN'\n" +
                "  - 'BLACKSTONE_SLAB'\n" +
                "  - 'BLACKSTONE_STAIRS'\n" +
                "  - 'BLACKSTONE_WALL'\n" +
                "  - 'BLACK_BANNER'\n" +
                "  - 'BLACK_BED'\n" +
                "  - 'BLACK_CARPET'\n" +
                "  - 'BLACK_GLAZED_TERRACOTTA'\n" +
                "  - 'BLACK_STAINED_GLASS'\n" +
                "  - 'BLACK_STAINED_GLASS_PANE'\n" +
                "  - 'BLACK_TERRACOTTA'\n" +
                "  - 'BLACK_WALL_BANNER'\n" +
                "  - 'BLACK_WOOL'\n" +
                "  - 'BLUE_BANNER'\n" +
                "  - 'BLUE_BED'\n" +
                "  - 'BLUE_CARPET'\n" +
                "  - 'BLUE_GLAZED_TERRACOTTA'\n" +
                "  - 'BLUE_ICE'\n" +
                "  - 'BLUE_ORCHID'\n" +
                "  - 'BLUE_STAINED_GLASS'\n" +
                "  - 'BLUE_STAINED_GLASS_PANE'\n" +
                "  - 'BLUE_TERRACOTTA'\n" +
                "  - 'BLUE_WALL_BANNER'\n" +
                "  - 'BLUE_WOOL'\n" +
                "  - 'BONE_BLOCK'\n" +
                "  - 'BRAIN_CORAL'\n" +
                "  - 'BRAIN_CORAL_BLOCK'\n" +
                "  - 'BRAIN_CORAL_FAN'\n" +
                "  - 'BRAIN_CORAL_WALL_FAN'\n" +
                "  - 'BRICK'\n" +
                "  - 'BRICK_SLAB'\n" +
                "  - 'BRICK_STAIRS'\n" +
                "  - 'BROWN_BANNER'\n" +
                "  - 'BROWN_BED'\n" +
                "  - 'BROWN_CARPET'\n" +
                "  - 'BROWN_GLAZED_TERRACOTTA'\n" +
                "  - 'BROWN_MUSHROOM_BLOCK'\n" +
                "  - 'BROWN_STAINED_GLASS'\n" +
                "  - 'BROWN_STAINED_GLASS_PANE'\n" +
                "  - 'BROWN_TERRACOTTA'\n" +
                "  - 'BROWN_WALL_BANNER'\n" +
                "  - 'BROWN_WOOL'\n" +
                "  - 'BUBBLE_CORAL'\n" +
                "  - 'BUBBLE_CORAL_BLOCK'\n" +
                "  - 'BUBBLE_CORAL_FAN'\n" +
                "  - 'BUBBLE_CORAL_WALL_FAN'\n" +
                "  - 'CARVED_PUMPKIN'\n" +
                "  - 'CAULDRON'\n" +
                "  - 'CHAIN'\n" +
                "  - 'CHEST'\n" +
                "  - 'CHIPPED_ANVIL'\n" +
                "  - 'CLAY'\n" +
                "  - 'COBBLESTONE_SLAB'\n" +
                "  - 'COBBLESTONE_STAIRS'\n" +
                "  - 'COBBLESTONE_WALL'\n" +
                "  - 'COBWEB'\n" +
                "  - 'CORNFLOWER'\n" +
                "  - 'CRAFTING_TABLE'\n" +
                "  - 'CREEPER_BANNER_PATTERN'\n" +
                "  - 'CREEPER_HEAD'\n" +
                "  - 'CREEPER_WALL_HEAD'\n" +
                "  - 'CRIMSON_DOOR'\n" +
                "  - 'CRIMSON_FENCE'\n" +
                "  - 'CRIMSON_FENCE_GATE'\n" +
                "  - 'CRIMSON_FUNGUS'\n" +
                "  - 'CRIMSON_ROOTS'\n" +
                "  - 'CRIMSON_SIGN'\n" +
                "  - 'CRIMSON_SLAB'\n" +
                "  - 'CRIMSON_STAIRS'\n" +
                "  - 'CRIMSON_TRAPDOOR'\n" +
                "  - 'CRIMSON_WALL_SIGN'\n" +
                "  - 'CUT_RED_SANDSTONE_SLAB'\n" +
                "  - 'CUT_SANDSTONE_SLAB'\n" +
                "  - 'CYAN_BANNER'\n" +
                "  - 'CYAN_BED'\n" +
                "  - 'CYAN_CARPET'\n" +
                "  - 'CYAN_GLAZED_TERRACOTTA'\n" +
                "  - 'CYAN_STAINED_GLASS'\n" +
                "  - 'CYAN_STAINED_GLASS_PANE'\n" +
                "  - 'CYAN_WALL_BANNER'\n" +
                "  - 'CYAN_WOOL'\n" +
                "  - 'DAMAGED_ANVIL'\n" +
                "  - 'DARK_OAK_DOOR'\n" +
                "  - 'DARK_OAK_FENCE'\n" +
                "  - 'DARK_OAK_FENCE_GATE'\n" +
                "  - 'DARK_OAK_SIGN'\n" +
                "  - 'DARK_OAK_SLAB'\n" +
                "  - 'DARK_OAK_STAIRS'\n" +
                "  - 'DARK_OAK_TRAPDOOR'\n" +
                "  - 'DARK_OAK_WALL_SIGN'\n" +
                "  - 'DARK_PRISMARINE_SLAB'\n" +
                "  - 'DARK_PRISMARINE_STAIRS'\n" +
                "  - 'DEAD_BRAIN_CORAL'\n" +
                "  - 'DEAD_BRAIN_CORAL_BLOCK'\n" +
                "  - 'DEAD_BRAIN_CORAL_FAN'\n" +
                "  - 'DEAD_BRAIN_CORAL_WALL_FAN'\n" +
                "  - 'DEAD_BUBBLE_CORAL'\n" +
                "  - 'DEAD_BUBBLE_CORAL_BLOCK'\n" +
                "  - 'DEAD_BUBBLE_CORAL_FAN'\n" +
                "  - 'DEAD_BUBBLE_CORAL_WALL_FAN'\n" +
                "  - 'DEAD_BUSH'\n" +
                "  - 'DEAD_FIRE_CORAL'\n" +
                "  - 'DEAD_FIRE_CORAL_BLOCK'\n" +
                "  - 'DEAD_FIRE_CORAL_FAN'\n" +
                "  - 'DEAD_FIRE_CORAL_WALL_FAN'\n" +
                "  - 'DEAD_HORN_CORAL'\n" +
                "  - 'DEAD_HORN_CORAL_BLOCK'\n" +
                "  - 'DEAD_HORN_CORAL_FAN'\n" +
                "  - 'DEAD_HORN_CORAL_WALL_FAN'\n" +
                "  - 'DEAD_TUBE_CORAL'\n" +
                "  - 'DEAD_TUBE_CORAL_BLOCK'\n" +
                "  - 'DEAD_TUBE_CORAL_FAN'\n" +
                "  - 'DEAD_TUBE_CORAL_WALL_FAN'\n" +
                "  - 'DIORITE_SLAB'\n" +
                "  - 'DIORITE_STAIRS'\n" +
                "  - 'DIORITE_WALL'\n" +
                "  - 'DRAGON_EGG'\n" +
                "  - 'DRAGON_HEAD'\n" +
                "  - 'DRAGON_WALL_HEAD'\n" +
                "  - 'ENDER_CHEST'\n" +
                "  - 'END_PORTAL_FRAME'\n" +
                "  - 'END_ROD'\n" +
                "  - 'END_STONE_BRICKS'\n" +
                "  - 'END_STONE_BRICK_SLAB'\n" +
                "  - 'END_STONE_BRICK_STAIRS'\n" +
                "  - 'END_STONE_BRICK_WALL'\n" +
                "  - 'FIRE_CORAL'\n" +
                "  - 'FIRE_CORAL_BLOCK'\n" +
                "  - 'FIRE_CORAL_FAN'\n" +
                "  - 'FIRE_CORAL_WALL_FAN'\n" +
                "  - 'FLETCHING_TABLE'\n" +
                "  - 'FLOWER_POT'\n" +
                "  - 'FLOWER_BANNER_PATTERN'\n" +
                "  - 'FURNACE'\n" +
                "  - 'GLASS'\n" +
                "  - 'GLASS_PANE'\n" +
                "  - 'GLOBE_BANNER_PATTERN'\n" +
                "  - 'GLOWSTONE'\n" +
                "  - 'GRANITE_SLAB'\n" +
                "  - 'GRANITE_STAIRS'\n" +
                "  - 'GRANITE_WALL'\n" +
                "  - 'GRASS'\n" +
                "  - 'GRASS_PATH'\n" +
                "  - 'GRAY_BANNER'\n" +
                "  - 'GRAY_BED'\n" +
                "  - 'GRAY_CARPET'\n" +
                "  - 'GRAY_GLAZED_TERRACOTTA'\n" +
                "  - 'GRAY_STAINED_GLASS'\n" +
                "  - 'GRAY_STAINED_GLASS_PANE'\n" +
                "  - 'GRAY_WALL_BANNER'\n" +
                "  - 'GRAY_WOOL'\n" +
                "  - 'GREEN_BANNER'\n" +
                "  - 'GREEN_BED'\n" +
                "  - 'GREEN_CARPET'\n" +
                "  - 'GREEN_GLAZED_TERRACOTTA'\n" +
                "  - 'GREEN_STAINED_GLASS'\n" +
                "  - 'GREEN_STAINED_GLASS_PANE'\n" +
                "  - 'GREEN_WALL_BANNER'\n" +
                "  - 'GREEN_WOOL'\n" +
                "  - 'GRINDSTONE'\n" +
                "  - 'HONEYCOMB_BLOCK'\n" +
                "  - 'HONEY_BLOCK'\n" +
                "  - 'HORN_CORAL'\n" +
                "  - 'HORN_CORAL_BLOCK'\n" +
                "  - 'HORN_CORAL_FAN'\n" +
                "  - 'HORN_CORAL_WALL_FAN'\n" +
                "  - 'ICE'\n" +
                "  - 'IRON_BARS'\n" +
                "  - 'IRON_DOOR'\n" +
                "  - 'IRON_TRAPDOOR'\n" +
                "  - 'ITEM_FRAME'\n" +
                "  - 'JACK_O_LANTERN'\n" +
                "  - 'JUKEBOX'\n" +
                "  - 'JUNGLE_DOOR'\n" +
                "  - 'JUNGLE_FENCE'\n" +
                "  - 'JUNGLE_FENCE_GATE'\n" +
                "  - 'JUNGLE_LEAVES'\n" +
                "  - 'JUNGLE_PRESSURE_PLATE'\n" +
                "  - 'JUNGLE_SIGN'\n" +
                "  - 'JUNGLE_SLAB'\n" +
                "  - 'JUNGLE_STAIRS'\n" +
                "  - 'JUNGLE_TRAPDOOR'\n" +
                "  - 'JUNGLE_WALL_SIGN'\n" +
                "  - 'LANTERN'\n" +
                "  - 'LECTERN'\n" +
                "  - 'LIGHT_GRAY_STAINED_GLASS'\n" +
                "  - 'LIGHT_BLUE_BANNER'\n" +
                "  - 'LIGHT_BLUE_BED'\n" +
                "  - 'LIGHT_BLUE_CARPET'\n" +
                "  - 'LIGHT_BLUE_GLAZED_TERRACOTTA'\n" +
                "  - 'LIGHT_BLUE_STAINED_GLASS'\n" +
                "  - 'LIGHT_BLUE_STAINED_GLASS_PANE'\n" +
                "  - 'LIGHT_BLUE_WALL_BANNER'\n" +
                "  - 'LIGHT_BLUE_WOOL'\n" +
                "  - 'LIGHT_GRAY_BANNER'\n" +
                "  - 'LIGHT_GRAY_BED'\n" +
                "  - 'LIGHT_GRAY_CARPET'\n" +
                "  - 'LIGHT_GRAY_GLAZED_TERRACOTTA'\n" +
                "  - 'LIGHT_GRAY_STAINED_GLASS_PANE'\n" +
                "  - 'LIGHT_GRAY_WALL_BANNER'\n" +
                "  - 'LIGHT_GRAY_WOOL'\n" +
                "  - 'LIGHT_WEIGHTED_PRESSURE_PLATE'\n" +
                "  - 'LILY_PAD'\n" +
                "  - 'LIME_BANNER'\n" +
                "  - 'LIME_BED'\n" +
                "  - 'LIME_CARPET'\n" +
                "  - 'LIME_GLAZED_TERRACOTTA'\n" +
                "  - 'LIME_STAINED_GLASS'\n" +
                "  - 'LIME_STAINED_GLASS_PANE'\n" +
                "  - 'LIME_WALL_BANNER'\n" +
                "  - 'LIME_WOOL'\n" +
                "  - 'LOOM'\n" +
                "  - 'MAGENTA_BANNER'\n" +
                "  - 'MAGENTA_BED'\n" +
                "  - 'MAGENTA_CARPET'\n" +
                "  - 'MAGENTA_STAINED_GLASS'\n" +
                "  - 'MAGENTA_STAINED_GLASS_PANE'\n" +
                "  - 'MAGENTA_WALL_BANNER'\n" +
                "  - 'MAGENTA_WOOL'\n" +
                "  - 'MOJANG_BANNER_PATTERN'\n" +
                "  - 'MOSSY_COBBLESTONE_SLAB'\n" +
                "  - 'MOSSY_COBBLESTONE_STAIRS'\n" +
                "  - 'MOSSY_COBBLESTONE_WALL'\n" +
                "  - 'MOSSY_STONE_BRICK_SLAB'\n" +
                "  - 'MOSSY_STONE_BRICK_STAIRS'\n" +
                "  - 'MOSSY_STONE_BRICK_WALL'\n" +
                "  - 'MUSHROOM_STEM'\n" +
                "  - 'MYCELIUM'\n" +
                "  - 'NETHER_BRICKS'\n" +
                "  - 'NETHER_BRICK_FENCE'\n" +
                "  - 'NETHER_BRICK_SLAB'\n" +
                "  - 'NETHER_BRICK_STAIRS'\n" +
                "  - 'NETHER_BRICK_WALL'\n" +
                "  - 'NETHER_SPROUTS'\n" +
                "  - 'NETHER_WART_BLOCK'\n" +
                "  - 'NOTE_BLOCK'\n" +
                "  - 'OAK_DOOR'\n" +
                "  - 'OAK_FENCE'\n" +
                "  - 'OAK_FENCE_GATE'\n" +
                "  - 'OAK_LEAVES'\n" +
                "  - 'OAK_PRESSURE_PLATE'\n" +
                "  - 'OAK_SIGN'\n" +
                "  - 'OAK_SLAB'\n" +
                "  - 'OAK_STAIRS'\n" +
                "  - 'OAK_TRAPDOOR'\n" +
                "  - 'OAK_WALL_SIGN'\n" +
                "  - 'ORANGE_BANNER'\n" +
                "  - 'ORANGE_BED'\n" +
                "  - 'ORANGE_CARPET'\n" +
                "  - 'ORANGE_GLAZED_TERRACOTTA'\n" +
                "  - 'ORANGE_STAINED_GLASS'\n" +
                "  - 'ORANGE_STAINED_GLASS_PANE'\n" +
                "  - 'ORANGE_WALL_BANNER'\n" +
                "  - 'ORANGE_WOOL'\n" +
                "  - 'PACKED_ICE'\n" +
                "  - 'PAINTING'\n" +
                "  - 'PETRIFIED_OAK_SLAB'\n" +
                "  - 'PIGLIN_BANNER_PATTERN'\n" +
                "  - 'PINK_BANNER'\n" +
                "  - 'PINK_BED'\n" +
                "  - 'PINK_CARPET'\n" +
                "  - 'PINK_GLAZED_TERRACOTTA'\n" +
                "  - 'PINK_STAINED_GLASS'\n" +
                "  - 'PINK_STAINED_GLASS_PANE'\n" +
                "  - 'PINK_WALL_BANNER'\n" +
                "  - 'PINK_WOOL'\n" +
                "  - 'POLISHED_ANDESITE_SLAB'\n" +
                "  - 'POLISHED_ANDESITE_STAIRS'\n" +
                "  - 'POLISHED_BLACKSTONE_BRICKS'\n" +
                "  - 'POLISHED_BLACKSTONE_BRICK_SLAB'\n" +
                "  - 'POLISHED_BLACKSTONE_BRICK_STAIRS'\n" +
                "  - 'POLISHED_BLACKSTONE_BRICK_WALL'\n" +
                "  - 'POLISHED_BLACKSTONE_PRESSURE_PLATE'\n" +
                "  - 'POLISHED_BLACKSTONE_SLAB'\n" +
                "  - 'POLISHED_BLACKSTONE_STAIRS'\n" +
                "  - 'POLISHED_BLACKSTONE_WALL'\n" +
                "  - 'POLISHED_DIORITE_SLAB'\n" +
                "  - 'POLISHED_DIORITE_STAIRS'\n" +
                "  - 'POLISHED_GRANITE_SLAB'\n" +
                "  - 'POLISHED_GRANITE_STAIRS'\n" +
                "  - 'PRISMARINE'\n" +
                "  - 'PRISMARINE_BRICKS'\n" +
                "  - 'PRISMARINE_BRICK_SLAB'\n" +
                "  - 'PRISMARINE_BRICK_STAIRS'\n" +
                "  - 'PRISMARINE_SLAB'\n" +
                "  - 'PRISMARINE_STAIRS'\n" +
                "  - 'PRISMARINE_WALL'\n" +
                "  - 'PURPLE_BANNER'\n" +
                "  - 'PURPLE_BED'\n" +
                "  - 'PURPLE_CARPET'\n" +
                "  - 'PURPLE_GLAZED_TERRACOTTA'\n" +
                "  - 'PURPLE_STAINED_GLASS'\n" +
                "  - 'PURPLE_STAINED_GLASS_PANE'\n" +
                "  - 'PURPLE_WALL_BANNER'\n" +
                "  - 'PURPLE_WOOL'\n" +
                "  - 'PURPUR_SLAB'\n" +
                "  - 'PURPUR_STAIRS'\n" +
                "  - 'QUARTZ_BLOCK'\n" +
                "  - 'QUARTZ_BRICKS'\n" +
                "  - 'QUARTZ_PILLAR'\n" +
                "  - 'QUARTZ_SLAB'\n" +
                "  - 'QUARTZ_STAIRS'\n" +
                "  - 'RED_BANNER'\n" +
                "  - 'RED_BED'\n" +
                "  - 'RED_CARPET'\n" +
                "  - 'RED_GLAZED_TERRACOTTA'\n" +
                "  - 'RED_MUSHROOM_BLOCK'\n" +
                "  - 'RED_NETHER_BRICKS'\n" +
                "  - 'RED_NETHER_BRICK_SLAB'\n" +
                "  - 'RED_NETHER_BRICK_STAIRS'\n" +
                "  - 'RED_NETHER_BRICK_WALL'\n" +
                "  - 'RED_SANDSTONE_SLAB'\n" +
                "  - 'RED_SANDSTONE_STAIRS'\n" +
                "  - 'RED_SANDSTONE_WALL'\n" +
                "  - 'RED_STAINED_GLASS'\n" +
                "  - 'RED_STAINED_GLASS_PANE'\n" +
                "  - 'RED_WALL_BANNER'\n" +
                "  - 'RED_WOOL'\n" +
                "  - 'SANDSTONE_SLAB'\n" +
                "  - 'SANDSTONE_STAIRS'\n" +
                "  - 'SANDSTONE_WALL'\n" +
                "  - 'SCAFFOLDING'\n" +
                "  - 'SEAGRASS'\n" +
                "  - 'SEA_LANTERN'\n" +
                "  - 'SHROOMLIGHT'\n" +
                "  - 'SKELETON_SKULL'\n" +
                "  - 'SKULL_BANNER_PATTERN'\n" +
                "  - 'SMITHING_TABLE'\n" +
                "  - 'SMOKER'\n" +
                "  - 'SMOOTH_QUARTZ_SLAB'\n" +
                "  - 'SMOOTH_QUARTZ_STAIRS'\n" +
                "  - 'SMOOTH_RED_SANDSTONE_SLAB'\n" +
                "  - 'SMOOTH_RED_SANDSTONE_STAIRS'\n" +
                "  - 'SMOOTH_SANDSTONE_SLAB'\n" +
                "  - 'SMOOTH_SANDSTONE_STAIRS'\n" +
                "  - 'SMOOTH_STONE_SLAB'\n" +
                "  - 'SNOW'\n" +
                "  - 'SNOW_BLOCK'\n" +
                "  - 'SOUL_CAMPFIRE'\n" +
                "  - 'SOUL_LANTERN'\n" +
                "  - 'SOUL_TORCH'\n" +
                "  - 'SPONGE'\n" +
                "  - 'SPRUCE_DOOR'\n" +
                "  - 'SPRUCE_FENCE'\n" +
                "  - 'SPRUCE_FENCE_GATE'\n" +
                "  - 'SPRUCE_LEAVES'\n" +
                "  - 'SPRUCE_PRESSURE_PLATE'\n" +
                "  - 'SPRUCE_SIGN'\n" +
                "  - 'SPRUCE_SLAB'\n" +
                "  - 'SPRUCE_STAIRS'\n" +
                "  - 'SPRUCE_TRAPDOOR'\n" +
                "  - 'SPRUCE_WALL_SIGN'\n" +
                "  - 'STONECUTTER'\n" +
                "  - 'STONE_BRICKS'\n" +
                "  - 'STONE_BRICK_SLAB'\n" +
                "  - 'STONE_BRICK_STAIRS'\n" +
                "  - 'STONE_BRICK_WALL'\n" +
                "  - 'STONE_PRESSURE_PLATE'\n" +
                "  - 'STONE_SLAB'\n" +
                "  - 'STONE_STAIRS'\n" +
                "  - 'TALL_GRASS'\n" +
                "  - 'TALL_SEAGRASS'\n" +
                "  - 'TRAPPED_CHEST'\n" +
                "  - 'TUBE_CORAL'\n" +
                "  - 'TUBE_CORAL_FAN'\n" +
                "  - 'TUBE_CORAL_WALL_FAN'\n" +
                "  - 'WARPED_DOOR'\n" +
                "  - 'WARPED_FENCE'\n" +
                "  - 'WARPED_FENCE_GATE'\n" +
                "  - 'WARPED_PRESSURE_PLATE'\n" +
                "  - 'WARPED_SIGN'\n" +
                "  - 'WARPED_SLAB'\n" +
                "  - 'WARPED_STAIRS'\n" +
                "  - 'WARPED_TRAPDOOR'\n" +
                "  - 'WARPED_WART_BLOCK'\n" +
                "  - 'WET_SPONGE'\n" +
                "  - 'WHITE_BANNER'\n" +
                "  - 'WHITE_BED'\n" +
                "  - 'WHITE_CARPET'\n" +
                "  - 'WHITE_GLAZED_TERRACOTTA'\n" +
                "  - 'WHITE_STAINED_GLASS'\n" +
                "  - 'WHITE_STAINED_GLASS_PANE'\n" +
                "  - 'WHITE_WALL_BANNER'\n" +
                "  - 'WHITE_WOOL'\n" +
                "  - 'WITHER_SKELETON_SKULL'\n" +
                "  - 'YELLOW_BANNER'\n" +
                "  - 'YELLOW_BED'\n" +
                "  - 'YELLOW_CARPET'\n" +
                "  - 'YELLOW_GLAZED_TERRACOTTA'\n" +
                "  - 'YELLOW_STAINED_GLASS'\n" +
                "  - 'YELLOW_STAINED_GLASS_PANE'\n" +
                "  - 'YELLOW_WALL_BANNER'\n" +
                "  - 'YELLOW_WOOL'\n" +
                "  - 'ZOMBIE_HEAD'\n" +
                "different:\n" +
                " title: \"&2&lDifferent\"\n" +
                " slot: 13\n" +
                " material: \"MUSIC_DISC_13\"\n" +
                " items: \n" +
                "  - 'BLACK_DYE'\n" +
                "  - 'BLUE_DYE'\n" +
                "  - 'BROWN_DYE'\n" +
                "  - 'CAMPFIRE'\n" +
                "  - 'CARTOGRAPHY_TABLE'\n" +
                "  - 'CARVED_PUMPKIN'\n" +
                "  - 'CAULDRON'\n" +
                "  - 'CLAY_BALL'\n" +
                "  - 'COD_BUCKET'\n" +
                "  - 'CYAN_DYE'\n" +
                "  - 'ENDER_EYE'\n" +
                "  - 'EXPERIENCE_BOTTLE'\n" +
                "  - 'FILLED_MAP'\n" +
                "  - 'FIREWORK_STAR'\n" +
                "  - 'FIRE_CHARGE'\n" +
                "  - 'GRAY_DYE'\n" +
                "  - 'GREEN_DYE'\n" +
                "  - 'LADDER'\n" +
                "  - 'LAVA_BUCKET'\n" +
                "  - 'LEAD'\n" +
                "  - 'LIGHT_BLUE_DYE'\n" +
                "  - 'LIGHT_GRAY_DYE'\n" +
                "  - 'LIME_DYE'\n" +
                "  - 'MAGENTA_DYE'\n" +
                "  - 'MAP'\n" +
                "  - 'MUSIC_DISC_11'\n" +
                "  - 'MUSIC_DISC_13'\n" +
                "  - 'MUSIC_DISC_BLOCKS'\n" +
                "  - 'MUSIC_DISC_CAT'\n" +
                "  - 'MUSIC_DISC_CHIRP'\n" +
                "  - 'MUSIC_DISC_FAR'\n" +
                "  - 'MUSIC_DISC_MALL'\n" +
                "  - 'MUSIC_DISC_MELLOHI'\n" +
                "  - 'MUSIC_DISC_PIGSTEP'\n" +
                "  - 'MUSIC_DISC_STAL'\n" +
                "  - 'MUSIC_DISC_STRAD'\n" +
                "  - 'MUSIC_DISC_WAIT'\n" +
                "  - 'MUSIC_DISC_WARD'\n" +
                "  - 'NAME_TAG'\n" +
                "  - 'NETHER_PORTAL'\n" +
                "  - 'ORANGE_DYE'\n" +
                "  - 'PINK_DYE'\n" +
                "  - 'PLAYER_HEAD'\n" +
                "  - 'POPPED_CHORUS_FRUIT'\n" +
                "  - 'POTTED_ACACIA_SAPLING'\n" +
                "  - 'POTTED_ALLIUM'\n" +
                "  - 'POTTED_AZURE_BLUET'\n" +
                "  - 'POTTED_BAMBOO'\n" +
                "  - 'POTTED_BIRCH_SAPLING'\n" +
                "  - 'POTTED_BLUE_ORCHID'\n" +
                "  - 'POTTED_BROWN_MUSHROOM'\n" +
                "  - 'POTTED_CACTUS'\n" +
                "  - 'POTTED_CORNFLOWER'\n" +
                "  - 'POTTED_CRIMSON_FUNGUS'\n" +
                "  - 'POTTED_DANDELION'\n" +
                "  - 'POTTED_DARK_OAK_SAPLING'\n" +
                "  - 'POTTED_DEAD_BUSH'\n" +
                "  - 'POTTED_FERN'\n" +
                "  - 'POTTED_JUNGLE_SAPLING'\n" +
                "  - 'POTTED_LILY_OF_THE_VALLEY'\n" +
                "  - 'POTTED_OAK_SAPLING'\n" +
                "  - 'POTTED_ORANGE_TULIP'\n" +
                "  - 'POTTED_OXEYE_DAISY'\n" +
                "  - 'POTTED_PINK_TULIP'\n" +
                "  - 'POTTED_POPPY'\n" +
                "  - 'POTTED_RED_MUSHROOM'\n" +
                "  - 'POTTED_RED_TULIP'\n" +
                "  - 'POTTED_SPRUCE_SAPLING'\n" +
                "  - 'POTTED_WARPED_FUNGUS'\n" +
                "  - 'POTTED_WARPED_ROOTS'\n" +
                "  - 'POTTED_WHITE_TULIP'\n" +
                "  - 'POTTED_WITHER_ROSE'\n" +
                "  - 'PUFFERFISH_BUCKET'\n" +
                "  - 'PURPLE_DYE'\n" +
                "  - 'RABBIT_FOOT'\n" +
                "  - 'RED_DYE'\n" +
                "  - 'RESPAWN_ANCHOR'\n" +
                "  - 'SADDLE'\n" +
                "  - 'SALMON_BUCKET'\n" +
                "  - 'SNOW'\n" +
                "  - 'SNOWBALL'\n" +
                "  - 'SNOW_BLOCK'\n" +
                "  - 'SOUL_CAMPFIRE'\n" +
                "  - 'STICK'\n" +
                "  - 'TORCH'\n" +
                "  - 'TROPICAL_FISH_BUCKET'\n" +
                "  - 'WHITE_DYE'\n" +
                "  - 'YELLOW_DYE'\n" +
                "enchanting:\n" +
                " title: \"&2&lEnchanting\"\n" +
                " slot: 14\n" +
                " material: \"ENCHANTED_BOOK\"\n" +
                " items: \n" +
                "  - 'BOOK'\n" +
                "  - 'BOOKSHELF'\n" +
                "  - 'ENCHANTED_BOOK'\n" +
                "  - 'ENCHANTING_TABLE'\n" +
                "  - 'KNOWLEDGE_BOOK'\n" +
                "  - 'LAPIS_BLOCK'\n" +
                "  - 'LAPIS_LAZULI'\n" +
                "  - 'PAPER'\n" +
                "  - 'WRITABLE_BOOK'\n" +
                "  - 'WRITTEN_BOOK'\n" +
                "food:\n" +
                " title: \"&2&lFood\"\n" +
                " slot: 15\n" +
                " material: \"COOKED_PORKCHOP\"\n" +
                " items: \n" +
                "  - 'APPLE'\n" +
                "  - 'BAKED_POTATO'\n" +
                "  - 'BEEF'\n" +
                "  - 'BEETROOT'\n" +
                "  - 'BEETROOT_SOUP'\n" +
                "  - 'BOWL'\n" +
                "  - 'BREAD'\n" +
                "  - 'BROWN_MUSHROOM'\n" +
                "  - 'CAKE'\n" +
                "  - 'CHICKEN'\n" +
                "  - 'CHORUS_FRUIT'\n" +
                "  - 'COD'\n" +
                "  - 'COOKED_BEEF'\n" +
                "  - 'COOKED_CHICKEN'\n" +
                "  - 'COOKED_COD'\n" +
                "  - 'COOKED_MUTTON'\n" +
                "  - 'COOKED_PORKCHOP'\n" +
                "  - 'COOKED_RABBIT'\n" +
                "  - 'COOKED_SALMON'\n" +
                "  - 'COOKIE'\n" +
                "  - 'DRIED_KELP'\n" +
                "  - 'DRIED_KELP_BLOCK'\n" +
                "  - 'EGG'\n" +
                "  - 'ENCHANTED_GOLDEN_APPLE'\n" +
                "  - 'GOLDEN_APPLE'\n" +
                "  - 'GOLDEN_CARROT'\n" +
                "  - 'HAY_BLOCK'\n" +
                "  - 'HONEY_BOTTLE'\n" +
                "  - 'MELON_SLICE'\n" +
                "  - 'MILK_BUCKET'\n" +
                "  - 'MUSHROOM_STEW'\n" +
                "  - 'MUTTON'\n" +
                "  - 'POISONOUS_POTATO'\n" +
                "  - 'PORKCHOP'\n" +
                "  - 'POTATO'\n" +
                "  - 'PUFFERFISH'\n" +
                "  - 'PUMPKIN_PIE'\n" +
                "  - 'RABBIT'\n" +
                "  - 'RABBIT_STEW'\n" +
                "  - 'ROTTEN_FLESH'\n" +
                "  - 'SALMON'\n" +
                "  - 'SUSPICIOUS_STEW'\n" +
                "  - 'SWEET_BERRIES'\n" +
                "  - 'TROPICAL_FISH'\n" +
                "  - 'WHEAT'\n" +
                "fuel:\n" +
                " title: \"&2&lFuel\"\n" +
                " slot: 16\n" +
                " material: \"COAL\"\n" +
                " items: \n" +
                "  - 'BAMBOO'\n" +
                "  - 'CHARCOAL'\n" +
                "  - 'COAL'\n" +
                "  - 'COAL_BLOCK'\n" +
                "jewel:\n" +
                " title: \"&2&lJewelry\"\n" +
                " slot: 17\n" +
                " material: \"DIAMOND\"\n" +
                " items: \n" +
                "  - 'ANCIENT_DEBRIS'\n" +
                "  - 'ANVIL'\n" +
                "  - 'BEACON'\n" +
                "  - 'BEDROCK'\n" +
                "  - 'BLACK_SHULKER_BOX'\n" +
                "  - 'BLAZE_SPAWN_EGG'\n" +
                "  - 'BLUE_SHULKER_BOX'\n" +
                "  - 'BONE_BLOCK'\n" +
                "  - 'BROWN_SHULKER_BOX'\n" +
                "  - 'CHIPPED_ANVIL'\n" +
                "  - 'COAL_BLOCK'\n" +
                "  - 'CONDUIT'\n" +
                "  - 'CREEPER_HEAD'\n" +
                "  - 'CREEPER_WALL_HEAD'\n" +
                "  - 'CRYING_OBSIDIAN'\n" +
                "  - 'CYAN_SHULKER_BOX'\n" +
                "  - 'DAMAGED_ANVIL'\n" +
                "  - 'DIAMOND'\n" +
                "  - 'DIAMOND_BLOCK'\n" +
                "  - 'DRAGON_EGG'\n" +
                "  - 'DRAGON_HEAD'\n" +
                "  - 'DRAGON_WALL_HEAD'\n" +
                "  - 'EMERALD'\n" +
                "  - 'EMERALD_BLOCK'\n" +
                "  - 'ENCHANTED_GOLDEN_APPLE'\n" +
                "  - 'FLINT'\n" +
                "  - 'GOLD_BLOCK'\n" +
                "  - 'GOLD_INGOT'\n" +
                "  - 'GOLD_NUGGET'\n" +
                "  - 'GRAY_SHULKER_BOX'\n" +
                "  - 'GREEN_SHULKER_BOX'\n" +
                "  - 'HEART_OF_THE_SEA'\n" +
                "  - 'IRON_BLOCK'\n" +
                "  - 'IRON_INGOT'\n" +
                "  - 'IRON_NUGGET'\n" +
                "  - 'LAPIS_BLOCK'\n" +
                "  - 'LAPIS_LAZULI'\n" +
                "  - 'LIGHT_BLUE_SHULKER_BOX'\n" +
                "  - 'LIGHT_GRAY_SHULKER_BOX'\n" +
                "  - 'LIME_SHULKER_BOX'\n" +
                "  - 'LODESTONE'\n" +
                "  - 'MAGENTA_SHULKER_BOX'\n" +
                "  - 'NAUTILUS_SHELL'\n" +
                "  - 'NETHERITE_BLOCK'\n" +
                "  - 'NETHERITE_INGOT'\n" +
                "  - 'NETHERITE_SCRAP'\n" +
                "  - 'NETHER_STAR'\n" +
                "  - 'ORANGE_SHULKER_BOX'\n" +
                "  - 'PINK_SHULKER_BOX'\n" +
                "  - 'POISONOUS_POTATO'\n" +
                "  - 'PURPLE_SHULKER_BOX'\n" +
                "  - 'QUARTZ'\n" +
                "  - 'RABBIT_FOOT'\n" +
                "  - 'RED_SHULKER_BOX'\n" +
                "  - 'SCUTE'\n" +
                "  - 'SHULKER_BOX'\n" +
                "  - 'SKELETON_SKULL'\n" +
                "  - 'SPAWNER'\n" +
                "  - 'SPONGE'\n" +
                "  - 'TOTEM_OF_UNDYING'\n" +
                "  - 'WET_SPONGE'\n" +
                "  - 'WHITE_SHULKER_BOX'\n" +
                "  - 'WITHER_SKELETON_SKULL'\n" +
                "  - 'YELLOW_SHULKER_BOX'\n" +
                "  - 'ZOMBIE_HEAD'\n" +
                "loot:\n" +
                " title: \"&2&lLoot from mobs\"\n" +
                " slot: 18\n" +
                " material: \"FEATHER\"\n" +
                " items: \n" +
                "  - 'ARROW'\n" +
                "  - 'BONE'\n" +
                "  - 'COAL'\n" +
                "  - 'ENDER_PEARL'\n" +
                "  - 'FEATHER'\n" +
                "  - 'GHAST_TEAR'\n" +
                "  - 'GUNPOWDER'\n" +
                "  - 'HONEYCOMB'\n" +
                "  - 'HONEY_BLOCK'\n" +
                "  - 'HONEY_BOTTLE'\n" +
                "  - 'INK_SAC'\n" +
                "  - 'LEATHER'\n" +
                "  - 'MAGMA_CREAM'\n" +
                "  - 'NETHER_STAR'\n" +
                "  - 'PHANTOM_MEMBRANE'\n" +
                "  - 'PRISMARINE_CRYSTALS'\n" +
                "  - 'PRISMARINE_SHARD'\n" +
                "  - 'RABBIT_FOOT'\n" +
                "  - 'RABBIT_HIDE'\n" +
                "  - 'REDSTONE'\n" +
                "  - 'ROTTEN_FLESH'\n" +
                "  - 'SCUTE'\n" +
                "  - 'SHULKER_SHELL'\n" +
                "  - 'SKELETON_SKULL'\n" +
                "  - 'SLIME_BALL'\n" +
                "  - 'SPECTRAL_ARROW'\n" +
                "  - 'SPIDER_EYE'\n" +
                "  - 'STICK'\n" +
                "  - 'STRING'\n" +
                "  - 'SUGAR'\n" +
                "  - 'TOTEM_OF_UNDYING'\n" +
                "  - 'TURTLE_EGG'\n" +
                "  - 'WITHER_ROSE'\n" +
                "  - 'WITHER_SKELETON_SKULL'\n" +
                "  - 'ZOMBIE_HEAD'\n" +
                "mechanisms:\n" +
                " title: \"&2&lMechanisms\"\n" +
                " slot: 19\n" +
                " material: \"TNT\"\n" +
                " items: \n" +
                "  - 'ACACIA_BUTTON'\n" +
                "  - 'ACACIA_PRESSURE_PLATE'\n" +
                "  - 'ACACIA_TRAPDOOR'\n" +
                "  - 'ACTIVATOR_RAIL'\n" +
                "  - 'ANVIL'\n" +
                "  - 'BARREL'\n" +
                "  - 'BIRCH_BUTTON'\n" +
                "  - 'BIRCH_PRESSURE_PLATE'\n" +
                "  - 'BLAST_FURNACE'\n" +
                "  - 'BREWING_STAND'\n" +
                "  - 'CHEST'\n" +
                "  - 'CHEST_MINECART'\n" +
                "  - 'COMPARATOR'\n" +
                "  - 'COMPOSTER'\n" +
                "  - 'CRIMSON_BUTTON'\n" +
                "  - 'CRIMSON_PRESSURE_PLATE'\n" +
                "  - 'CRIMSON_TRAPDOOR'\n" +
                "  - 'DAMAGED_ANVIL'\n" +
                "  - 'DARK_OAK_BUTTON'\n" +
                "  - 'DARK_OAK_PRESSURE_PLATE'\n" +
                "  - 'DARK_OAK_TRAPDOOR'\n" +
                "  - 'DAYLIGHT_DETECTOR'\n" +
                "  - 'DETECTOR_RAIL'\n" +
                "  - 'DISPENSER'\n" +
                "  - 'DROPPER'\n" +
                "  - 'FURNACE'\n" +
                "  - 'FURNACE_MINECART'\n" +
                "  - 'HEAVY_WEIGHTED_PRESSURE_PLATE'\n" +
                "  - 'HONEY_BLOCK'\n" +
                "  - 'HOPPER'\n" +
                "  - 'HOPPER_MINECART'\n" +
                "  - 'IRON_DOOR'\n" +
                "  - 'IRON_TRAPDOOR'\n" +
                "  - 'JUKEBOX'\n" +
                "  - 'JUNGLE_BUTTON'\n" +
                "  - 'JUNGLE_PRESSURE_PLATE'\n" +
                "  - 'JUNGLE_TRAPDOOR'\n" +
                "  - 'LEVER'\n" +
                "  - 'LIGHT_WEIGHTED_PRESSURE_PLATE'\n" +
                "  - 'NOTE_BLOCK'\n" +
                "  - 'OAK_BUTTON'\n" +
                "  - 'OAK_PRESSURE_PLATE'\n" +
                "  - 'OAK_TRAPDOOR'\n" +
                "  - 'OBSERVER'\n" +
                "  - 'PISTON'\n" +
                "  - 'POLISHED_BLACKSTONE_BUTTON'\n" +
                "  - 'POLISHED_BLACKSTONE_PRESSURE_PLATE'\n" +
                "  - 'POWERED_RAIL'\n" +
                "  - 'RAIL'\n" +
                "  - 'REDSTONE'\n" +
                "  - 'REDSTONE_BLOCK'\n" +
                "  - 'REDSTONE_LAMP'\n" +
                "  - 'REDSTONE_TORCH'\n" +
                "  - 'REPEATER'\n" +
                "  - 'SLIME_BLOCK'\n" +
                "  - 'SPRUCE_BUTTON'\n" +
                "  - 'SPRUCE_PRESSURE_PLATE'\n" +
                "  - 'SPRUCE_TRAPDOOR'\n" +
                "  - 'STICKY_PISTON'\n" +
                "  - 'STONE_BUTTON'\n" +
                "  - 'STONE_PRESSURE_PLATE'\n" +
                "  - 'TARGET'\n" +
                "  - 'TNT'\n" +
                "  - 'TNT_MINECART'\n" +
                "  - 'TRIPWIRE_HOOK'\n" +
                "  - 'WARPED_BUTTON'\n" +
                "  - 'WARPED_PRESSURE_PLATE'\n" +
                "  - 'WARPED_TRAPDOOR'\n" +
                "ores:\n" +
                " title: \"&2&lOres\"\n" +
                " slot: 20\n" +
                " material: \"GOLD_ORE\"\n" +
                " items:\n" +
                "  - 'COAL_ORE'\n" +
                "  - 'DIAMOND_ORE'\n" +
                "  - 'EMERALD_ORE'\n" +
                "  - 'GILDED_BLACKSTONE'\n" +
                "  - 'GOLD_ORE'\n" +
                "  - 'IRON_ORE'\n" +
                "  - 'LAPIS_ORE'\n" +
                "  - 'NETHER_GOLD_ORE'\n" +
                "  - 'NETHER_QUARTZ_ORE'\n" +
                "  - 'REDSTONE_ORE'\n" +
                "plants:\n" +
                " title: \"&2&lPlants and Organics\"\n" +
                " slot: 21\n" +
                " material: \"WHEAT_SEEDS\"\n" +
                " items: \n" +
                "  - 'ACACIA_LEAVES'\n" +
                "  - 'ACACIA_SAPLING'\n" +
                "  - 'ALLIUM'\n" +
                "  - 'APPLE'\n" +
                "  - 'AZURE_BLUET'\n" +
                "  - 'BAMBOO'\n" +
                "  - 'BAMBOO_SAPLING'\n" +
                "  - 'BEETROOTS'\n" +
                "  - 'BEETROOT_SEEDS'\n" +
                "  - 'BIRCH_LEAVES'\n" +
                "  - 'BIRCH_SAPLING'\n" +
                "  - 'BLUE_ORCHID'\n" +
                "  - 'BONE_MEAL'\n" +
                "  - 'CACTUS'\n" +
                "  - 'CARROT'\n" +
                "  - 'CHORUS_FLOWER'\n" +
                "  - 'CHORUS_PLANT'\n" +
                "  - 'COCOA_BEANS'\n" +
                "  - 'CORNFLOWER'\n" +
                "  - 'CRIMSON_ROOTS'\n" +
                "  - 'DANDELION'\n" +
                "  - 'DARK_OAK_LEAVES'\n" +
                "  - 'DARK_OAK_SAPLING'\n" +
                "  - 'DIRT'\n" +
                "  - 'FARMLAND'\n" +
                "  - 'FERN'\n" +
                "  - 'GRASS'\n" +
                "  - 'GRASS_BLOCK'\n" +
                "  - 'HAY_BLOCK'\n" +
                "  - 'JUNGLE_LEAVES'\n" +
                "  - 'JUNGLE_SAPLING'\n" +
                "  - 'KELP'\n" +
                "  - 'LARGE_FERN'\n" +
                "  - 'LILAC'\n" +
                "  - 'LILY_OF_THE_VALLEY'\n" +
                "  - 'LILY_PAD'\n" +
                "  - 'MELON'\n" +
                "  - 'MELON_SEEDS'\n" +
                "  - 'NETHER_SPROUTS'\n" +
                "  - 'NETHER_WART'\n" +
                "  - 'OAK_LEAVES'\n" +
                "  - 'OAK_SAPLING'\n" +
                "  - 'ORANGE_TULIP'\n" +
                "  - 'OXEYE_DAISY'\n" +
                "  - 'PEONY'\n" +
                "  - 'PINK_TULIP'\n" +
                "  - 'PODZOL'\n" +
                "  - 'POISONOUS_POTATO'\n" +
                "  - 'POPPY'\n" +
                "  - 'PUMPKIN'\n" +
                "  - 'PUMPKIN_SEEDS'\n" +
                "  - 'RED_MUSHROOM'\n" +
                "  - 'RED_TULIP'\n" +
                "  - 'ROSE_BUSH'\n" +
                "  - 'SEAGRASS'\n" +
                "  - 'SEA_PICKLE'\n" +
                "  - 'SPRUCE_LEAVES'\n" +
                "  - 'SPRUCE_SAPLING'\n" +
                "  - 'SUGAR_CANE'\n" +
                "  - 'SUNFLOWER'\n" +
                "  - 'SWEET_BERRIES'\n" +
                "  - 'SWEET_BERRY_BUSH'\n" +
                "  - 'TALL_GRASS'\n" +
                "  - 'TALL_SEAGRASS'\n" +
                "  - 'TWISTING_VINES'\n" +
                "  - 'VINE'\n" +
                "  - 'WARPED_FUNGUS'\n" +
                "  - 'WARPED_ROOTS'\n" +
                "  - 'WEEPING_VINES'\n" +
                "  - 'WHEAT_SEEDS'\n" +
                "  - 'WHITE_TULIP'\n" +
                "  - 'WITHER_ROSE'\n" +
                "potions:\n" +
                " title: \"&2&lPotions\"\n" +
                " slot: 22\n" +
                " material: \"POTION\"\n" +
                " items: \n" +
                "  - 'LINGERING_POTION'\n" +
                "  - 'POTION'\n" +
                "  - 'SPLASH_POTION'\n" +
                "spawn_egg:\n" +
                " title: \"&2&lSpawn Eggs\"\n" +
                " slot: 23\n" +
                " material: \"CREEPER_SPAWN_EGG\"\n" +
                " items: \n" +
                "  - 'BAT_SPAWN_EGG'\n" +
                "  - 'BEE_SPAWN_EGG'\n" +
                "  - 'CAT_SPAWN_EGG'\n" +
                "  - 'CAVE_SPIDER_SPAWN_EGG'\n" +
                "  - 'CHICKEN_SPAWN_EGG'\n" +
                "  - 'COD_SPAWN_EGG'\n" +
                "  - 'COW_SPAWN_EGG'\n" +
                "  - 'CREEPER_SPAWN_EGG'\n" +
                "  - 'DOLPHIN_SPAWN_EGG'\n" +
                "  - 'DONKEY_SPAWN_EGG'\n" +
                "  - 'DROWNED_SPAWN_EGG'\n" +
                "  - 'ELDER_GUARDIAN_SPAWN_EGG'\n" +
                "  - 'ENDERMAN_SPAWN_EGG'\n" +
                "  - 'ENDERMITE_SPAWN_EGG'\n" +
                "  - 'EVOKER_SPAWN_EGG'\n" +
                "  - 'FOX_SPAWN_EGG'\n" +
                "  - 'GHAST_SPAWN_EGG'\n" +
                "  - 'GUARDIAN_SPAWN_EGG'\n" +
                "  - 'HOGLIN_SPAWN_EGG'\n" +
                "  - 'HORSE_SPAWN_EGG'\n" +
                "  - 'HUSK_SPAWN_EGG'\n" +
                "  - 'LLAMA_SPAWN_EGG'\n" +
                "  - 'MAGMA_CUBE_SPAWN_EGG'\n" +
                "  - 'MOOSHROOM_SPAWN_EGG'\n" +
                "  - 'MULE_SPAWN_EGG'\n" +
                "  - 'OCELOT_SPAWN_EGG'\n" +
                "  - 'PANDA_SPAWN_EGG'\n" +
                "  - 'PARROT_SPAWN_EGG'\n" +
                "  - 'PHANTOM_SPAWN_EGG'\n" +
                "  - 'PIGLIN_BRUTE_SPAWN_EGG'\n" +
                "  - 'PIGLIN_SPAWN_EGG'\n" +
                "  - 'PIG_SPAWN_EGG'\n" +
                "  - 'PILLAGER_SPAWN_EGG'\n" +
                "  - 'POLAR_BEAR_SPAWN_EGG'\n" +
                "  - 'PUFFERFISH_SPAWN_EGG'\n" +
                "  - 'RABBIT_SPAWN_EGG'\n" +
                "  - 'RAVAGER_SPAWN_EGG'\n" +
                "  - 'SALMON_SPAWN_EGG'\n" +
                "  - 'SHEEP_SPAWN_EGG'\n" +
                "  - 'SHULKER_SPAWN_EGG'\n" +
                "  - 'SILVERFISH_SPAWN_EGG'\n" +
                "  - 'SKELETON_HORSE_SPAWN_EGG'\n" +
                "  - 'SKELETON_SPAWN_EGG'\n" +
                "  - 'SLIME_SPAWN_EGG'\n" +
                "  - 'SPIDER_SPAWN_EGG'\n" +
                "  - 'SQUID_SPAWN_EGG'\n" +
                "  - 'STRAY_SPAWN_EGG'\n" +
                "  - 'STRIDER_SPAWN_EGG'\n" +
                "  - 'TRADER_LLAMA_SPAWN_EGG'\n" +
                "  - 'TROPICAL_FISH_SPAWN_EGG'\n" +
                "  - 'TURTLE_SPAWN_EGG'\n" +
                "  - 'VEX_SPAWN_EGG'\n" +
                "  - 'VILLAGER_SPAWN_EGG'\n" +
                "  - 'VINDICATOR_SPAWN_EGG'\n" +
                "  - 'WANDERING_TRADER_SPAWN_EGG'\n" +
                "  - 'WITCH_SPAWN_EGG'\n" +
                "  - 'WITHER_SKELETON_SPAWN_EGG'\n" +
                "  - 'WOLF_SPAWN_EGG'\n" +
                "  - 'ZOGLIN_SPAWN_EGG'\n" +
                "  - 'ZOMBIE_HORSE_SPAWN_EGG'\n" +
                "  - 'ZOMBIE_SPAWN_EGG'\n" +
                "  - 'ZOMBIE_VILLAGER_SPAWN_EGG'\n" +
                "  - 'ZOMBIFIED_PIGLIN_SPAWN_EGG'\n" +
                "tools:\n" +
                " title: \"&2&lTools\"\n" +
                " slot: 24\n" +
                " material: \"DIAMOND_PICKAXE\"\n" +
                " items: \n" +
                "  - 'BUCKET'\n" +
                "  - 'CARROT_ON_A_STICK'\n" +
                "  - 'CLOCK'\n" +
                "  - 'COMPASS'\n" +
                "  - 'DIAMOND_AXE'\n" +
                "  - 'DIAMOND_HOE'\n" +
                "  - 'DIAMOND_PICKAXE'\n" +
                "  - 'DIAMOND_SHOVEL'\n" +
                "  - 'FISHING_ROD'\n" +
                "  - 'FLINT_AND_STEEL'\n" +
                "  - 'GOLDEN_AXE'\n" +
                "  - 'GOLDEN_HOE'\n" +
                "  - 'GOLDEN_PICKAXE'\n" +
                "  - 'GOLDEN_SHOVEL'\n" +
                "  - 'IRON_AXE'\n" +
                "  - 'IRON_PICKAXE'\n" +
                "  - 'IRON_SHOVEL'\n" +
                "  - 'LAVA_BUCKET'\n" +
                "  - 'NETHERITE_AXE'\n" +
                "  - 'NETHERITE_HOE'\n" +
                "  - 'NETHERITE_PICKAXE'\n" +
                "  - 'NETHERITE_SHOVEL'\n" +
                "  - 'SHEARS'\n" +
                "  - 'STONE_AXE'\n" +
                "  - 'STONE_HOE'\n" +
                "  - 'STONE_PICKAXE'\n" +
                "  - 'STONE_SHOVEL'\n" +
                "  - 'WARPED_FUNGUS_ON_A_STICK'\n" +
                "  - 'WATER_BUCKET'\n" +
                "  - 'WOODEN_AXE'\n" +
                "  - 'WOODEN_HOE'\n" +
                "  - 'WOODEN_PICKAXE'\n" +
                "  - 'WOODEN_SHOVEL'\n" +
                "transport:\n" +
                " title: \"&2&lTransport\"\n" +
                " slot: 25\n" +
                " material: \"OAK_BOAT\"\n" +
                " items: \n" +
                "  - 'ACACIA_BOAT'\n" +
                "  - 'BIRCH_BOAT'\n" +
                "  - 'DARK_OAK_BOAT'\n" +
                "  - 'FIREWORK_ROCKET'\n" +
                "  - 'JUNGLE_BOAT'\n" +
                "  - 'MINECART'\n" +
                "  - 'OAK_BOAT'\n" +
                "  - 'SADDLE'\n" +
                "  - 'SPRUCE_BOAT'\n" +
                "weapon:\n" +
                " title: \"&2&lWeapon\"\n" +
                " slot: 26\n" +
                " material: \"DIAMOND_SWORD\"\n" +
                " items: \n" +
                "  - 'BOW'\n" +
                "  - 'CROSSBOW'\n" +
                "  - 'DIAMOND_AXE'\n" +
                "  - 'DIAMOND_SWORD'\n" +
                "  - 'END_CRYSTAL'\n" +
                "  - 'GOLDEN_AXE'\n" +
                "  - 'GOLDEN_SWORD'\n" +
                "  - 'IRON_AXE'\n" +
                "  - 'IRON_SWORD'\n" +
                "  - 'NETHERITE_AXE'\n" +
                "  - 'NETHERITE_SWORD'\n" +
                "  - 'SHIELD'\n" +
                "  - 'SPECTRAL_ARROW'\n" +
                "  - 'STONE_AXE'\n" +
                "  - 'STONE_SWORD'\n" +
                "  - 'TIPPED_ARROW'\n" +
                "  - 'TRIDENT'\n" +
                "  - 'WOODEN_AXE'\n" +
                "  - 'WOODEN_SWORD'\n";

        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter(configFileName));
            writer.write(yml_str);
            writer.close();
        } catch (IOException e){
            e.printStackTrace();
        }
    }

}
